### ISSUE TITLE
Help me, MariaDB Crashes and I dont know why.

### ISSUE THREAD

**Issue by Emporea** [MariaDB/mariadb-docker#307]
I use Nextcloud(18 currently). Everything was working fine until this day when i got this message when accessing my cloud via the webbrowser.

Internal Server Error  The server encountered an internal error  and was unable to complete your request. Please contact the server  administrator if this error reappears multiple times, please include the  technical details below in your report. More details can be found in  the server log.

I am using docker, or more specific docker compose for almost 2 years now. fpm alpine, splitted into 5 parts: mariadb, redis, app, web, and cron.
```yaml
version: '3'

services:
  nextcloud_db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  nextcloud_redis:
    image: redis:alpine
    restart: always

  nextcloud_app:
    build: ./app
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
    env_file:
      - db.env
    depends_on:
      - nextcloud_db
      - nextcloud_redis

  nextcloud_web:
    build: ./web
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
    depends_on:
      - nextcloud_app

  nextcloud_cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - nextcloud_redis

volumes:
  nextcloud_db:
  nextcloud:
```

The mariadb one has an error currently.

![image](https://user-images.githubusercontent.com/21969523/81991409-777ddf80-9641-11ea-824b-5101118d3975.png)

this is in the docker logs. this sounds way too complicated for me and i have no clue.

I have not made any changes to my system. I need my system working. It is in productive use.

let me know if you know anything related to this problem or if I should provide further data or what i should look for to get this fixed. Thank you.
