### ISSUE TITLE
Cannot open shared library.

### ISSUE THREAD

**Issue by EmberNight** [MariaDB/mariadb-docker#322]
Versions:

* Docker	version 19.03.12-ce, build 48a66213fe
* mariadb	version 10.5

Docker Compose used to create the issue

```yml
mariadb:
  container_name: mariadb
  image: mariadb
  environment:
    MYSQL_DATABASE_FILE: database_name
    MYSQL_PASSWORD_FILE: user_pass
    MYSQL_ROOT_PASSWORD_FILE: root_pass
    MYSQL_USER_FILE: username
  volumes:
    - path/to/data:/var/lib/mysql
    - path/to/plugin:/usr/lib/mysql/plugin
  command:
    - --transaction-isolation=READ-COMMITTED
    - --plugin-load-add=aws_key_management
  restart: unless-stopped
```

When trying to load aws_key_management.so in the logs I received one error line stating

```
ERROR 1126 (HY000): Can't open shared library '/usr/lib/mysql/plugin/aws_key_management.so' (errno: 2, libcurl.so.4: cannot open shared object file: No such file or directory)
```

I then used **docker exec -it mariadb bash** and accessed the database as root and entered 
```sql
INSTALL PLUGIN aws_key_management SONAME 'aws_key_management.so';
```

This returned the same error code above. 

After some research I installed the package **libcurl4** in the container. This allowed me to add the plugin with the **INSTALL PLUGIN** command.

After the container is removed for an update this change is reverted and displays a new error.

```
[ERROR] mysqld: Can't open shared library '/usr/lib/mysql/plugin/aws_key_management.so' (errno: 22, libcurl.so.4: cannot open shared object fi
le: No such file or directory)
```
This is caused because mariadb is trying to access the plugin from its mysql:plugin table since we were able to add it to the table in the previous step. This is just the same problem in a different location and is solve by way by updating libcurl in the container again.

I am hoping to use the aws plugin in the container.
