### ISSUE TITLE
MariaDb latest image doesn't access my environment variable

### ISSUE THREAD

**Issue by JonathanMM** [MariaDB/mariadb-docker#336]
Hello everybody,
I try to run a mariadb docker image using docker composer, but, it seems doesn't accept my environment variable, specially the one which define the root password. If I use the same configuration with mysql image, everything works without issue.
```yaml
version: "3"
services:
  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  db_data: {}
```
Logs:
[docker_logs.log](https://github.com/docker-library/mariadb/files/5684544/docker_logs.log)

I'm on last version of ubuntu.
Can you help me?
Regards
