### ISSUE TITLE
cant connect to DB from another container

### ISSUE THREAD

**Issue by mrjoli021** [MariaDB/mariadb-docker#392]
I am running MariaDB 10.5 with the following compose file.  If I connect to the cli of the DB container I am able to connect to the db with the user.  But the Python container is not able to.  I keep getting the following error messages on the console of the MariadB container.

[Warning] Aborted connection 11 to db: 'db' user: 'db_user' host: '172.29.0.3' (Got an error reading communication packets).

```
---
version: "3.7"
services:

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_api
    restart: unless-stopped
    volumes:
      - ./DATA/mariadb_api/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: dbPassword

    healthcheck:
      test: "/usr/bin/mysql --user=root --password=rootPassword --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  python:
    depends_on:
    - mariadb
    build:
      context: ./App
    container_name: python3.9_api
    restart: unless-stopped
    #volumes:
    #- ./DATA/python3.9/:/app
```
