### ISSUE TITLE
unable to access Mariadb using docker-compose & Nginx Proxy

### ISSUE THREAD

**Issue by andrej19897436** [MariaDB/mariadb-docker#410]
Hi,

I am trying to setup Mariadb with docker compose and use Nginx proxy to handle the connections. The issue i have is that if i publish mariadb port as localhost only i cannot access it remotely. Is there a way to chanel it through the proxy or am i talking nonsense?

Thanks!

Docker compose file:
```
version: '3'

services:
  maria:
    image: mariadb
    container_name: maria
    restart: always
    ports:
      - "127.0.0.1:3307:3306" # exposing the port only to local host
      # - "3307:3306"
    networks:
      - overlay
    volumes:
      - vTest:/var/lib/mysql
    environment:
      MARIADB_USER: "foobar"
      MARIADB_PASSWORD: "foobar"
      MARIADB_ROOT_PASSWORD: "foobar"
      MYSQL_DATABASE: "test_db"
      VIRTUAL_HOST: "maria.lan"
      VIRTUAL_PORT: "3307"
  
  nginx:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - overlay
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  vTest:
    name: vTest
    # external: true
    driver_opts:
      type: "none"
      o: "bind"
      device: "/app/mariadb/db"

networks:
  overlay:
    external: true
    name: overlay
```
