### ISSUE TITLE
Error 1133 trying to run docker container in Linode VPS

### ISSUE THREAD

**Issue by hacefresko** [MariaDB/mariadb-docker#427]
Hello there. I have an application which uses a mariadb container and it's specified in the `docker-compose.yml` file as the following:

```
  [...]
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=<root_password>
      - MARIADB_DATABASE=<db_name>
      - MARIADB_USER=<user>
      - MARIADB_PASSWORD=<password>
    volumes:
      - ./sql/bagley.sql:/docker-entrypoint-initdb.d/bagley.sql
    network_mode: "host"
    expose: 
      - 3306
  [...]
```

Everything works fine in my ubuntu machine. However, I tried to run the same application in a Linode server but all I got was the following error regarding the mariadb container:

```
[...]
mariadb_1  | Version: '10.7.3-MariaDB-1:10.7.3+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
mariadb_1  | 2022-04-14 16:19:27+00:00 [Note] [Entrypoint]: Temporary server started.
mariadb_1  | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
mariadb_1  | Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
mariadb_1  | Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
mariadb_1  | 2022-04-14 16:19:29+00:00 [Note] [Entrypoint]: Securing system users (equivalent to running mysql_secure_installation)
mariadb_1  | ERROR 1133 (28000) at line 10: Can't find any matching row in the user table
bagley_mariadb_1 exited with code 1
```

I found that the line it's referring to is [this one](https://github.com/MariaDB/mariadb-docker/blob/bf522faed0b15da89dc40dbcd2390d423ab2adb7/docker-entrypoint.sh#L343). 
Also, if I remove the `network_mode: "host"` from the docker-compose file, everything works as expected (but I need it for my application). I have read some posts about modyfing the script that produces the error, however, that would mean that the docker image would no longer be that portable for me so I would like to know what is going on in the server.

Thanks.
