### ISSUE TITLE
Add env var (E.g. MARIADB_EXTRA_FLAGS) to pass extra arguments to mariadb

### ISSUE THREAD

**Issue by mirekphd** [MariaDB/mariadb-docker#445]
Please add a useful option to pass extra command-line arguments to `mariadb` at startup.

For instance, in case of [bitnami/mariadb](https://hub.docker.com/r/bitnami/mariadb/) passing extra command-line flags to the `mariadb` command is possible through the following env var:

```
    MARIADB_EXTRA_FLAGS: Flags to be appended to the startup command. No defaults

$ docker run --name mariadb -e ALLOW_EMPTY_PASSWORD=yes -e MARIADB_EXTRA_FLAGS='--max-connect-errors=1000 --max_connections=155' bitnami/mariadb:latest
```
[See bitnami-docker-mariadb README.md](https://github.com/bitnami/bitnami-docker-mariadb/blob/master/README.md)

**Comment by grooverdan** [comment]
You can already use any extra command line variables with:

```
docker run --name mariadb -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 mariadb --max-connect-errors=1000 --max_connections=155
```

See [docker hub docs](https://hub.docker.com/_/mariadb/) (Configuration without a cnf file section).

**Comment by mirekphd** [comment]
Agreed, adding such an env var  may seem redundant given that the container starts from MySQL server daemon (see its [Dockerfile](https://github.com/MariaDB/mariadb-docker/blob/master/10.5/Dockerfile#L139) ):
```
CMD ["mysqld"]
```

Let's test how passing extra arguments to the container's server simply as additional container startup arguments works, verifying it using `--version` argument as an example.

1. In the simplest scenario of a `docker run` of the unmodified official container from `library/mariadb`: **OK**
```
$ docker run --rm --name mariadb -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 mariadb:10.5 --version
mysqld  Ver 10.5.16-MariaDB-1:10.5.16+maria~focal for debian-linux-gnu on x86_64 (mariadb.org binary distribution)
```

2. In a more complex scenario, where the `docker run` is applied to a custom container based on `mariadb:10.5`: **OK**
```
$ docker run --rm --name mariadb -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 mirekphd/ml-mariadb:latest --version
mysqld  Ver 10.5.16-MariaDB-1:10.5.16+maria~focal for debian-linux-gnu on x86_64 (mariadb.org binary distribution)
```

**Comment by mirekphd** [comment]
Thank you @[grooverdan](https://github.com/grooverdan)! Now our migration to the official `mariadb` (caused by constant security issues in `bitnami/mariadb`, reported to Bitnami devs without much success) can be completed successfully.

**Comment by mirekphd** [comment]
A few more notes for the Kubernetes deployments:

* Passing multiple arguments simultaneously requires strings separated with commas (passing a single string like the one accepted by the Bitnami `MARIADB_EXTRA_FLAGS` variable is a Docker syntax error leading to `mysqld` startup error - `Unknown suffix ','`). The correct way:
```yaml
objects:
  - kind: DeploymentConfig
[..]
    spec:
[..]
        template:
[..]
          spec:
            containers:
            - image: ${CONTAINER_REGISTRY}/${CONTAINER_REPO}/${CONTAINER_NAME}:${CONTAINER_TAG}
[..]
              name: ml-mariadb-dev-node${NODE_NUMBER}
              # command: ["mysqld"]
              # args: ["--version"]
              args: ["--max-connect-errors=1200", "--max_connections=600"]
```
* You can use DB client (`mysql`, which should be installed in any `mariadb` container from any source) to verify the correctness of your custom arguments, such as connections settings in the above:
```sql
> select @@global.max_connections;
> select @@global.max_connect_errors;
```
