### ISSUE TITLE
How to set max_allowed_packet ?

### ISSUE THREAD

**Issue by tgbv** [MariaDB/mariadb-docker#467]
How do I specify the `max_allowed_packet` option? I tried the following docker-compose but it did not work:
```yml
version: '3.7'

services:
  mariadb:
    image: mariadb:10.9.3
    command: --max_allowed_packet=5GB
    volumes:
      - "./backend_db/mariadb.storage:/var/lib/mysql"
    ports:
      - "3306:3306"
    env_file: ./backend_db/mariadb.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```
