### ISSUE TITLE
MariaDB IGNORES my environment variables

### ISSUE THREAD

**Issue by DimitriDR** [MariaDB/mariadb-docker#482]
Hello,

I spent hours to struggle with Nextcloud setup because MariaDB container doesn't allow connections from other hosts, but I found the real problem is that MariaDB completely ignores what I put in my Docker Compose.

```
version: "3.9"

services:
  db:
      image: mariadb:latest
      container_name: nextcloud-db
      restart: unless-stopped
      environment:
        - MARIADB_ROOT_HOST="%"
        - MARIADB_ROOT_PASSWORD=nextcloud
        - MARIADB_DATABASE=nextcloud
        - MARIADB_USER=nextcloud
        - MARIADB_PASSWORD=nextcloud
      volumes:
        - /nextcloud-db/:/var/lib/mysql
      networks:
        - nextcloud-network

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    depends_on:
      - db
    links:
      - db
    ports:
      - 64246:80
    volumes:
      - /nextcloud/:/var/www/html
    networks:
      - nextcloud-network

networks:
  nextcloud-network:
    name: nextcloud-network
    driver: bridge
```

WHY?

When I do: ``SHOW DATABASES;`` I only have this:

```
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (0.000 sec)
```

It didn't created my database, I understand why I can't connect from any other containers despite the `MYSQL_ROOT_HOST="%"`
