### ISSUE TITLE
Hangs on Initializing

### ISSUE THREAD

**Issue by BrodyStone21** [MariaDB/mariadb-docker#487]
Hello, I'm trying to use mariadb with freshrss and bookstack. I can get mariadb:10.5 to work fine, but when stopping and removing the containers, deleting the old database files, and attempting to recreate everything, the database containers hang on initializing. Here is my compose for bookstack and bookstack_db. 

```
services:
  bookstack:
    container_name: bookstack
    restart: unless-stopped
    image: linuxserver/bookstack
    environment:
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - DB_PASSWORD=bookstackpass
      - DB_DATABASE=bookstackapp
      - APP_URL="bookstackurl.com"
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ubuntu/.config/bookstack:/config
    ports:
      - 6875:80
      - 3306:3306
    networks:
      proxy:
    depends_on:
      - bookstack_db
  bookstack_db:
    container_name: bookstack_db
    restart: unless-stopped
    image: mariadb:10.5
    environment:
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=bookstackpass
      - MYSQL_ROOT_PASSWORD=bookstackpass
      - TZ=America/Indianapolis
    volumes:
      - /mnt/WD_White/Server_Stuff/Databases/bookstack_db:/var/lib/mysql
    networks:
      proxy:
```

ouput of `docker logs bookstack_db -f`

```
2023-02-10 20:40:37-05:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.10.3+maria~ubu2204 started.
2023-02-10 20:40:41-05:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-02-10 20:40:41-05:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:10.10.3+maria~ubu2204 started.
2023-02-10 20:40:42-05:00 [Note] [Entrypoint]: Initializing database files
```

The exact same issue occurs when attempting to use the latest version of mariadb instead of 10.5. Both containers are just waiting for the database to be available. Happy to provide any additional information if you think it would be helpful.

EDIT: Can someone tell me if changing all the environmental variables from `MYSQL_*` to `MARIADB_*` does anything? Which is better? MySQL or MariaDB?

EDIT 2: It finally initialized! Any reason it takes so much longer than version 10.5 to get up and going?
