### ISSUE TITLE
mysql: command not found

### ISSUE THREAD

**Issue by Tanguy-Magnaudet** [MariaDB/mariadb-docker#524]
Hello,

I'm trying to init my db with a .sh file (because I want to fetch Env variable), put it tells me mysql command doesn't exists. :

```yaml
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: ./docker/Dockerfile-mariadb.dockerfile
    restart: always
    networks:
      - heracles
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_HERACLES=$DB_HERACLES
    volumes:
      - "./data/sql:/var/lib/mysql"
  ```
  
  The Dockerfile : 
  
  ```Dockerfile
FROM mariadb:11.0.2

# Add your shell script into the container
ADD ./scripts/initdb.sh /docker-entrypoint-initdb.d/initdb.sh

# Give it the necessary permissions
RUN chmod +x /docker-entrypoint-initdb.d/initdb.sh
```

And the initdb.sh :  

```sh
mysql -u root -e "CREATE DATABASE IF NOT EXISTS $DB_NAME; GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USER@'%' IDENTIFIED BY '$DB_PASSWORD';"
mysql -u root -e "CREATE DATABASE IF NOT EXISTS $DB_HERACLES; GRANT ALL PRIVILEGES ON $DB_HERACLES.* TO $DB_USER@'%' IDENTIFIED BY '$DB_PASSWORD';"
mysql -u root -e "FLUSH PRIVILEGES;"
```

Any idea why it doesn't work ?
