### ISSUE TITLE
Dashes in username are not allowed

### ISSUE THREAD

**Issue by dieechtenilente** [MariaDB/mariadb-docker#558]
Creating the following docker container

```
version: '2'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=apassword
      - MYSQL_PASSWORD=apassword
      - MYSQL_DATABASE=123-username-456
      - MYSQL_USER=123-username-456
```

results in a weird container with no 123-username-456 created.
