### ISSUE TITLE
Fresh container, fails tc.log and fails permissions

### ISSUE THREAD

**Issue by Daviid-P** [MariaDB/mariadb-docker#581]
```
version: '3'

services:
  openfire:
    image: nasqueron/openfire
    restart: "unless-stopped"
    depends_on:
        mysql:
            condition: service_healthy
            restart: true
    mem_reservation: "1G"
    mem_limit: "1G"
    ports:
      - "32780:9090/tcp"
      - "32781:9091/tcp"
      - "32782:5222/tcp"
      - "32783:7777/tcp"
      - "32784:7070/tcp"
    volumes:
      - /container_data/openfire:/var/lib/openfire
    environment:
      TZ: "Europe/Madrid"
      DAEMON_OPTS: -Xms32m -Xmx128m -Xss128k -Xoss128k -XX:ThreadStackSize=128 -XX:+PrintGCDetails -Xloggc:/var/log/openfire/gc.log -XX:+HeapDumpOnOutOfMemoryError
    networks:
      - openfire-net
  mysql:
    image: mariadb:latest
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: openfire
        MYSQL_USER: openfire
        MYSQL_PASSWORD: openfire
        MARIADB_AUTO_UPGRADE: 1
    healthcheck:
      interval: 5s
      retries: 5
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 5s
    ports:
      - "32788:3306/tcp"
    volumes:
      - /container_data/openfire/mysql:/var/lib/mysql
    restart: always
    networks:
      - openfire-net

networks:
  openfire-net:
    driver: bridge
```

If I start from scratch I get this error:

```
$ docker compose up -d --build
[+] Running 16/16
 ✔ openfire 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                  10.1s
   ✔ 1fe172e4850f Pull complete                                                                                                                        1.3s
   ✔ 44d3aa8d0766 Pull complete                                                                                                                        0.5s
   ✔ 6ce99fdf16e8 Pull complete                                                                                                                        5.8s
   ✔ b359cf6c1f08 Pull complete                                                                                                                        2.0s
   ✔ ccbc1cd82910 Pull complete                                                                                                                        1.6s
   ✔ b4388e81cff4 Pull complete                                                                                                                        2.0s
 ✔ mysql 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                   10.4s
   ✔ a8b1c5f80c2d Pull complete                                                                                                                        2.7s
   ✔ d452ffbe7f24 Pull complete                                                                                                                        2.0s
   ✔ 4ba312e23b80 Pull complete                                                                                                                        3.1s
   ✔ 5cff2f71f4cf Pull complete                                                                                                                        3.1s
   ✔ 7b3561610bd5 Pull complete                                                                                                                        3.5s
   ✔ 2be8c7da712f Pull complete                                                                                                                        5.9s
   ✔ 880bb1834a6d Pull complete                                                                                                                        3.9s
   ✔ 59853578cb11 Pull complete                                                                                                                        4.3s
[+] Running 3/3
 ✔ Network openfire_openfire-net  Created                                                                                                              0.2s
 ✘ Container openfire-mysql-1     Error                                                                                                                7.7s
 ✔ Container openfire-openfire-1  Created                                                                                                              0.0s
dependency failed to start: container openfire-mysql-1 is unhealthy
```

```
2024-05-21  8:55:58 0 [Note] Recovering after a crash using tc.log
2024-05-21  8:55:58 0 [ERROR] Bad magic header in tc log
2024-05-21  8:55:58 0 [ERROR] Crash recovery failed. Either correct the problem (if it's, for example, out of memory error) and restart, or delete tc log and start server with --tc-heuristic-recover={commit|rollback}
2024-05-21  8:55:58 0 [ERROR] Can't init tc log
2024-05-21  8:55:58 0 [ERROR] Aborting
```

If I do `docker compose down && docker compose up -d ; docker exec -it openfire-mysql-1 bash -c "ls -lah /var/lib/mysql/"`

I get 

```
total 155M
drwxr-x--- 6 mysql mysql  360 May 21 08:59 .
drwxr-xr-x 1 root  root  4.0K May  2 00:52 ..
-rwxr-x--- 1 mysql mysql  131 May 21 08:24 .my-healthcheck.cnf
-rwxr-x--- 1 mysql mysql  17M May 21 08:59 aria_log.00000001
-rwxr-x--- 1 mysql mysql   52 May 21 08:59 aria_log_control
-rwxr-x--- 1 mysql mysql 1.5K May 21 08:42 ib_buffer_pool
-rwxr-x--- 1 mysql mysql  96M May 21 08:42 ib_logfile0
-rwxr-x--- 1 mysql mysql  12M May 21 08:42 ibdata1
-rwxr-x--- 1 mysql mysql   14 May 21 08:24 mariadb_upgrade_info
-rwxr-x--- 1 mysql mysql    0 May 21 08:24 multi-master.info
drwxr-x--- 2 mysql mysql 1.8K May 21 08:24 mysql
drwxr-x--- 2 mysql mysql 1.4K May 21 08:33 openfire
drwxr-x--- 2 mysql mysql   60 May 21 08:24 performance_schema
drwxr-x--- 2 mysql mysql 2.1K May 21 08:24 sys
-rwxr-x--- 1 mysql mysql  24K May 21 08:42 tc.log
-rwxr-x--- 1 mysql mysql  10M May 21 08:42 undo001
-rwxr-x--- 1 mysql mysql  10M May 21 08:42 undo002
-rwxr-x--- 1 mysql mysql  10M May 21 08:42 undo003
```

And I can change the last command to `docker compose down && docker compose up -d ; docker exec -it openfire-mysql-1 bash -c "rm -f /var/lib/mysql/tc.log"` and remove the `tc.log` file, then the container starts ok `docker compose down && docker compose up -d`

`✔ Container openfire-mysql-1     Healthy`

BUT now the ownership of the files has changed:

```
root@5254726bbf64:/# ls -lah /var/lib/mysql/
total 167M
drwxr-x--- 6  101  101  400 May 21 09:00 .
drwxr-xr-x 1 root root 4.0K May  2 00:52 ..
-rwxr-x--- 1  101  101  131 May 21 08:24 .my-healthcheck.cnf
-rwxr-x--- 1  101  101  17M May 21 09:00 aria_log.00000001
-rwxr-x--- 1  101  101   52 May 21 09:00 aria_log_control
-rwxr-x--- 1  101  101    9 May 21 09:00 ddl_recovery.log
-rwxr-x--- 1  101  101 1.5K May 21 09:00 ib_buffer_pool
-rwxr-x--- 1  101  101  96M May 21 08:42 ib_logfile0
-rwxr-x--- 1  101  101  12M May 21 08:42 ibdata1
-rwxr-x--- 1  101  101  12M May 21 09:00 ibtmp1
-rwxr-x--- 1  101  101   14 May 21 08:24 mariadb_upgrade_info
-rwxr-x--- 1  101  101    0 May 21 08:24 multi-master.info
drwxr-x--- 2  101  101 1.8K May 21 08:24 mysql
drwxr-x--- 2  101  101 1.4K May 21 08:33 openfire
drwxr-x--- 2  101  101   60 May 21 08:24 performance_schema
drwxr-x--- 2  101  101 2.1K May 21 08:24 sys
-rwxr-x--- 1  101  101  24K May 21 09:00 tc.log
-rwxr-x--- 1  101  101  10M May 21 08:42 undo001
-rwxr-x--- 1  101  101  10M May 21 08:42 undo002
-rwxr-x--- 1  101  101  10M May 21 08:42 undo003
```

So I can't connect to any database due to permissions, fixable with `chown 999:999 -R /var/lib/mysql`

Any idea what might be going on here?
