### ISSUE TITLE
Issue with mounting a volume with `/*!999999\- enable the sandbox mode */ `

### ISSUE THREAD

**Issue by earthiverse** [MariaDB/mariadb-docker#584]
I have mariadb as a service in my `docker-compose.yml`.

```yaml
services:
  mariadb:
    image: mariadb:latest
    environment:
      # ...
    networks:
      # ...
    volumes:
      - ./schema/hospitality.sql:/docker-entrypoint-initdb.d/000-hospitality.sql
 ```

The SQL file in the `volumes` has `/*!999999\- enable the sandbox mode */ ` as the first line of the dump.

When I run docker compose to start my container, I get

```
mariadb-1     | 2024-05-28 09:06:41+09:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/000-hospitality.sql
mariadb-1     | ERROR at line 1: Unknown command '\-'.
mariadb-1 exited with code 1
```

If I remove the sandbox comment, it works fine.
```
mariadb-1     | 2024-05-28 09:07:48+09:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/000-hospitality.sql
mariadb-1     | 
mariadb-1     | 
mariadb-1     | 2024-05-28 09:07:48+09:00 [Note] [Entrypoint]: Stopping temporary server
...
```
