### ISSUE TITLE
healthcheck.sh cannot connect on 11.6-ubi

### ISSUE THREAD

**Issue by sebastianhelbig** [MariaDB/mariadb-docker#630]
Upgraded from `11.5` to `11.6-ubi`.

On mariadb startup, socket is created at `/run/mariadb/mariadb.sock`.

```
sh-5.1$ healthcheck.sh --connect --innodb_initialized --mariadbupgrade
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
```

**Comment by grooverdan** [comment]
I did find missing flock for `--mariadbupgrade` missing util-linux-core.

Couldn't replicate the socket;
```
++ _process_sql --skip-column-names -e 'select 1 from information_schema.ENGINES WHERE engine='\''innodb'\'' AND support in ('\''YES'\'', '\''DEFAULT'\'', '\''ENABLED'\'')'
++ mariadb --defaults-extra-file=/var/lib/mysql/.my-healthcheck.cnf --skip-ssl --skip-ssl-verify-server-cert --protocol socket -B --skip-column-names -e 'select 1 from information_schema.ENGINES WHERE engine='\''innodb'\'' AND support in ('\''YES'\'', '\''DEFAULT'\'', '\''ENABLED'\'')'
+ s=1
+ '[' 1 == 1 ']'
+ test=
+ shift
+ '[' 1 -gt 0 ']'
+ case "$1" in
+ test=mariadbupgrade
+ '[' -n mariadbupgrade ']'
+ _test_exists mariadbupgrade
+ declare -F mariadbupgrade
+ return 0
+ mariadbupgrade
+ local f=/var/lib/mysql/mariadb_upgrade_info
+ '[' -r /var/lib/mysql/mariadb_upgrade_info ']'
+ flock --exclusive --nonblock -n 9
/usr/local/bin/healthcheck.sh: line 238: flock: command not found
``

The socket location is defined in `/etc/my.cnf.d/docker.cnf`. Are you doing a manual configuration other than `/etc/mysql/conf.d`, the only location documented in https://hub.docker.com/_/mariadb/ - "Using a custom MariaDB configuration file"

**Comment by sebastianhelbig** [comment]
No custom configuration.

```
  db:
    command: --sql_mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    container_name: test-db
    environment:
      - MARIADB_AUTO_UPGRADE=true
      - MARIADB_DATABASE=test
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_PASSWORD=test
      - MARIADB_USER=test
      - TZ=Europe/Berlin
    expose:
      - "3306"
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 10s
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized", "--mariadbupgrade" ]
      timeout: 5s
    image: mariadb:11.6-ubi
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql
```
