### ISSUE TITLE
Remove usage of the `VOLUME` directive

### ISSUE THREAD

**Issue by polarathene** [MariaDB/mariadb-docker#639]
The `VOLUME` directive should be removed from the image build.
- Containers **already persist state internally** until the container is destroyed (_for example, an image upgraded to a new tag_).
- Proper persistence externally **should be explicit**.

https://github.com/MariaDB/mariadb-docker/blob/91ba0cc70228372663d3e8ec621b657f835afb07/Dockerfile.template#L137

https://github.com/MariaDB/mariadb-docker/blob/91ba0cc70228372663d3e8ec621b657f835afb07/Dockerfile-ubi.template#L103

---

Anonymous volumes are created when an image has a `VOLUME` directive. They will initialize by copying any of the existing content at the mount point (_unlike a bind mount volume which typically replaces content at the mount point_):
  - With `docker run --rm ...`, each container instance started will create a new anonymous volume. Without the `--rm`, these will accumulate pointlessly while the user may not be aware of this implicit waste on their system.
  - Docker Compose behaves differently, with additional logic to preserve the same anonymous volume across instances of the container for a given compose project.

---

The `VOLUME` directive provides **no value** to an image. It **only causes problems.**

For detailed justification, please see below context for my previous write-up on this subject:
- https://github.com/kanidm/kanidm/pull/2948
- https://github.com/ory/hydra/issues/3683
- https://github.com/caddyserver/caddy-docker/issues/118#issuecomment-1043908219
- [Example of implicit 2GB disk usage per container instance](https://github.com/rspamd/rspamd/issues/4400#issuecomment-1745881053) (_not applicable to images with empty `VOLUME` published, but clearly documents a `VOLUME` concern_)

**Comment by polarathene** [comment]
I am aware of a [past issue for this request](https://github.com/MariaDB/mariadb-docker/issues/495#issuecomment-1447341395) that [cited a bug report for why `VOLUME` was necessary](https://jira.mariadb.org/browse/MDEV-28751?focusedCommentId=231171&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-231171), but without sufficient information I am not sure how to reproduce it:

```yaml
# Attempt to reproduce error logs from MDEV-28751:
# https://jira.mariadb.org/browse/MDEV-28751?focusedCommentId=231171&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-231171

services:
  db:
    image: mariadb:10.6.8
    environment:
      MARIADB_ROOT_PASSWORD: secret
    configs:
      - source: custom_datadir
        target: /etc/mysql/mariadb.conf.d/01_customapp.cnf

# Use a custom config to set DB storage to a container location that isn't `VOLUME` mounted:
configs:
  custom_datadir:
    content: |
      [mariadb]
      datadir=/srv
```

[Another comment in that same bug report](https://jira.mariadb.org/browse/MDEV-28751?focusedCommentId=299208&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-299208) but from 2025, notes the issue appears to be fixed in newer versions of MariaDB. That's a bit misleading as I've used the exact version a past comment shared with logs, so something else in the environment is to blame.
